### ISSUE TITLE
Publishing on on specific topic

### ISSUE THREAD

**Issue by dnyaneshwarnadre** [jship/CpperoMQ-examples#1]
Was just wondering if there is example for sending message on specific topic i.e. counterpart of subscribe("XXX")
Thanks
Dnyaneshwar

**Comment by jship** [comment]
Hi @dnyaneshwarnadre, topics in ZMQ are sent as a user-defined prefix of the bytes in a message.  There is no special method to send on a specific topic - you must send the topic as the beginning part of your payload.  To get started, please see the re-implemented zguide examples for the weather update server and client:

- https://github.com/jship/CpperoMQ-examples/blob/d21031ad5bfd6874d941b14364320822574ccd91/zguide/wuserver.cpp#L36
- https://github.com/jship/CpperoMQ-examples/blob/d21031ad5bfd6874d941b14364320822574ccd91/zguide/wuclient.cpp#L23

In that example, the client subscribes to a zip code (like `10001`).  The message payload sent from the server has the form `<zip_code> <temperature> <relative_humidity>`, so the topic - the zip code - is the first portion of the payload.

**Comment by dnyaneshwarnadre** [comment]
Thanks Jason for quick reply !!
